import { IonButton, IonButtons, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonMenuButton, IonPage, IonSpinner, IonTitle, IonToast, IonToggle, IonToolbar } from "@ionic/react";
import { useEffect, useState } from "react";
import { precipitacionesConfigPut, precipitacionesGet, precipitacionesPeriodoDelete, precipitacionesPeriodoPut } from "../data/precipitaciones.repo";
import type { PeriodoPrecipitacion, PrecipitacionData } from "../types/precipitacion";
const MESES = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const nuevo = (): PeriodoPrecipitacion => ({ periodo: "", anioDesde: 2010, anioHasta: new Date().getFullYear() - 1, valores: Array(12).fill(0), publicado: false });
export default function PrecipitacionesPage() {
  const [data, setData] = useState<PrecipitacionData>(); const [periodo, setPeriodo] = useState(nuevo()); const [toast, setToast] = useState("");
  const [savingConfig, setSavingConfig] = useState(false); const [savingPeriodo, setSavingPeriodo] = useState(false);
  const cargar = () => precipitacionesGet().then(setData).catch(() => setToast("No se pudieron cargar los datos"));
  useEffect(() => { void cargar(); }, []);
  const guardarConfig = async () => { if (!data || savingConfig) return; setSavingConfig(true); try { await precipitacionesConfigPut(data.carmenAcumuladaMm, data.carmenVisible); setToast("Dato de Carmen guardado"); } catch { setToast("No se pudo guardar el dato de Carmen"); } finally { setSavingConfig(false); } };
  const guardarPeriodo = async () => { if (savingPeriodo) return; if (!periodo.periodo.trim()) { setToast("Indicá el nombre del período"); return; } setSavingPeriodo(true); try { await precipitacionesPeriodoPut(periodo); setPeriodo(nuevo()); await cargar(); setToast("Promedios guardados"); } catch { setToast("No se pudieron guardar los promedios"); } finally { setSavingPeriodo(false); } };
  return <IonPage><IonHeader><IonToolbar><IonButtons slot="start"><IonMenuButton /></IonButtons><IonTitle>Estadísticas de precipitación</IonTitle></IonToolbar></IonHeader><IonContent>
    {data && <><IonList><IonItem><IonLabel position="stacked">Lluvia acumulada en Carmen de Areco (mm)</IonLabel><IonInput type="number" value={data.carmenAcumuladaMm ?? ""} onIonInput={e => setData({...data,carmenAcumuladaMm:e.detail.value === "" ? null : Number(e.detail.value)})} /></IonItem><IonItem><IonLabel>Visible en la app</IonLabel><IonToggle checked={data.carmenVisible} onIonChange={e => setData({...data,carmenVisible:e.detail.checked})} /></IonItem></IonList><div className="ion-padding"><IonButton disabled={savingConfig} onClick={guardarConfig}>{savingConfig&&<IonSpinner slot="start" name="crescent"/>}{savingConfig?"Guardando…":"Guardar Carmen de Areco"}</IonButton></div></>}
    <section className="ion-padding"><h2>Promedio histórico</h2><IonList><IonItem><IonLabel position="stacked">Nombre del período</IonLabel><IonInput placeholder="Ej.: Promedio mensual 2010-2025" value={periodo.periodo} onIonInput={e=>setPeriodo({...periodo,periodo:e.detail.value??""})}/></IonItem><IonItem><IonLabel position="stacked">Año desde</IonLabel><IonInput type="number" value={periodo.anioDesde} onIonInput={e=>setPeriodo({...periodo,anioDesde:Number(e.detail.value)})}/></IonItem><IonItem><IonLabel position="stacked">Año hasta</IonLabel><IonInput type="number" value={periodo.anioHasta} onIonInput={e=>setPeriodo({...periodo,anioHasta:Number(e.detail.value)})}/></IonItem>{MESES.map((mes,i)=><IonItem key={mes}><IonLabel position="stacked">{mes} (mm)</IonLabel><IonInput type="number" value={periodo.valores[i]} onIonInput={e=>{const valores=[...periodo.valores];valores[i]=Number(e.detail.value);setPeriodo({...periodo,valores});}}/></IonItem>)}<IonItem><IonLabel>Publicado en la app</IonLabel><IonToggle checked={periodo.publicado} onIonChange={e=>setPeriodo({...periodo,publicado:e.detail.checked})}/></IonItem></IonList><IonButton expand="block" disabled={savingPeriodo} onClick={guardarPeriodo}>{savingPeriodo&&<IonSpinner slot="start" name="crescent"/>}{savingPeriodo?"Guardando…":"Guardar período"}</IonButton></section>
    {!!data?.periodos.length && <section className="ion-padding"><h2>Períodos cargados</h2><IonList>{data.periodos.map(p=><IonItem key={p.periodo}><IonLabel><h2>{p.periodo}</h2><p>{p.anioDesde}–{p.anioHasta} · {p.publicado?"Publicado":"Borrador"}</p></IonLabel><IonButton fill="clear" onClick={()=>setPeriodo(p)}>Editar</IonButton><IonButton color="danger" fill="clear" onClick={async()=>{await precipitacionesPeriodoDelete(p.periodo);await cargar();}}>Eliminar</IonButton></IonItem>)}</IonList></section>}
    <IonToast isOpen={!!toast} message={toast} duration={2400} onDidDismiss={()=>setToast("")}/>
  </IonContent></IonPage>;
}
